### ISSUE TITLE
[BUG] skill_resource_tests using incompatible version of neon_minerva

### ISSUE THREAD

**Issue by mikejgray** [NeonGeckoCom/.github#70]
### Description

https://github.com/OpenVoiceOS/ovos-skill-easter-eggs/actions/runs/7536978652/job/20515205017?pr=35

```
FAILED action/github/test/test_skill_resources.py::TestSkillResources::test_skill_setup - AttributeError: 'EasterEggsSkill' object has no attribute '_core_lang'. Did you mean: 'core_lang'?
```

### Steps to Reproduce

```yaml
  skill_resource_tests:
    uses: neongeckocom/.github/.github/workflows/skill_test_resources.yml@master
```

**Comment by NeonDaniel** [comment]
This should be resolved in v0.2.0 by https://github.com/NeonGeckoCom/neon-minerva/pull/15

**Comment by NeonDaniel** [comment]
@mikejgray can you confirm or recommend a method for me to confirm this is resolved?

**Comment by mikejgray** [comment]
@NeonDaniel Looks like I took Minerva out of the mix entirely in the repo where I originally reported this: https://github.com/OpenVoiceOS/ovos-skill-easter-eggs/blob/dev/test/test_skill.py

I think to test/replicate you'd use Minerva tests in an OVOSSkill skill. Not sure when I'll have a chance to check this out again. Most of my OVOSSkill-based stuff is off Minerva now
